export function ListDecoration1() {
  return (
    <ul className='listDecoration1'>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
    </ul>
  );
}
export function ListDecoration2() {
  return (
    <ul className='listDecoration2'>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
      <li>🟫</li>
    </ul>
  );
}
